AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Resources:
  OperationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref UsersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        DbWrite:
          Type: Api
          Properties:
            Path: /write
            Method: post
            RequestModel: !Ref InsertRequestModel
            RestApiId: !Ref ServerlessRestApi

  InsertRequestModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !Ref ServerlessRestApi
      ContentType: application/json
      Name: InsertRequestModel
      Schema:
        $schema: http://json-schema.org/draft-04/schema#
        title: InsertRequestSchema
        type: object
        properties:
          userId:
            type: string
          name:
            type: string
          surname:
            type: string
        required:
          - userId
          - name
          - surname

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RWUsersTable
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
